// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2srDYXl9ATpFweIEGPt6L4MfZHXfKx90',
    appId: '1:218245245376:web:44d7f2e4f5287fcf7e0025',
    messagingSenderId: '218245245376',
    projectId: 'padel-time-2460d',
    authDomain: 'padel-time-2460d.firebaseapp.com',
    storageBucket: 'padel-time-2460d.firebasestorage.app',
    measurementId: 'G-JHEH01XZLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgFuEcxUliTiwIjIdWJ30crWbSFbCI2Y',
    appId: '1:218245245376:android:13087d6bca2e3fa37e0025',
    messagingSenderId: '218245245376',
    projectId: 'padel-time-2460d',
    storageBucket: 'padel-time-2460d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2srDYXl9ATpFweIEGPt6L4MfZHXfKx90',
    appId: '1:218245245376:web:40ba303a5db72c837e0025',
    messagingSenderId: '218245245376',
    projectId: 'padel-time-2460d',
    authDomain: 'padel-time-2460d.firebaseapp.com',
    storageBucket: 'padel-time-2460d.firebasestorage.app',
    measurementId: 'G-6ZENJK7QCR',
  );
}
